include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: metric
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
  environment:
    url: https://${DD_TRAEFIK_SUBDOMAIN}.${DD_TRAEFIK_DOMAIN}
