global:
  telegram_api_url: '${TELEGRAM_URL}'

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ template "telegram-message-tmpl" . }}'
        parse_mode: '${TELEGRAM_PARSE_MODE}'
        disable_notifications: ${TELEGRAM_DISABLE_NOTIFICATIONS}

templates:
  - './telegram-message.tmpl'
