services:
  alertmanager:
    image: ${IMAGE_NAME:-prom/alertmanager}:${IMAGE_TAG:-latest}
    entrypoint: ${CONFIG_PATH}/entrypoint.sh
    command:
      - --config.file=${CONFIG_PATH}/alertmanager.yml
      - --storage.path=${DATA_PATH}
      - --web.external-url=https://${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
    environment:
      CONFIG_PATH:
      SLACK_URL:
      SLACK_CHANNEL:
      SLACK_USER:
    networks:
      metric-net:
      traefik-net:
    volumes:
      - data-vol:${DATA_PATH}
    configs:
      - source: entrypoint-config
        target: ${CONFIG_PATH}/entrypoint.sh
        mode: 0555
      - source: alertmanager-config
        target: ${CONFIG_PATH}/alertmanager-tmpl.yml
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}/-/healthy
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.alertmanager.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.alertmanager.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.middlewares.alertmanager-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.alertmanager.middlewares: alertmanager-auth
        traefik.http.services.alertmanager.loadbalancer.server.port: ${PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${DATA_VOL_DEVICE}

configs:
  entrypoint-config:
    name: ${ENTRYPOINT_CONFIG_NAME:-alertmanager-entrypoint}
    file: ./config/entrypoint.sh

  alertmanager-config:
    name: ${ALERTMANAGER_CONFIG_NAME:-alertmanager-config}
    file: ./config/alertmanager-tmpl.yml
